### ISSUE TITLE
ejabberd_auth_http unknown option 'auth_opts' will be likely ignored

### ISSUE THREAD

**Issue by richp10** [processone/ejabberd-contrib#116]
With latest ejabberd and contrib, Ejabberd compiled from source and ejabberd_auth_http sucesfully installed using ejabberdctl. 

    auth_method: http
    auth_opts:
      host: "http://192.168.0.200"
      path_prefix: "/auth/"

Ejabberd loads, with only the following error..

    @ejabberd_config:validate_opts:750 unknown option 'auth_opts' will be likely ignored

The auth module then does not work, presumably because it does not know where to find the api methods.

**Comment by badlop** [comment]
When ejabberd is starting, it calls ejabberd_config:start, which validates the options defined in the configuration file. For that, it asks erlang which erlang modules is ejabberd using (application:get_key(ejabberd, modules)). Then asks each module which options it accepts

The option auth_opts is accepted by the module ejabberd_auth_http, and that module is included in ejabberd by ext_mod. That module is not listed by erlang, so it doesn't have the chance to tell ejabberd_config which options it accepts.

Temporary solution: try to copy ejabberd_auth_http.beam to ejabberd's ebin/ directory, then install ejabberd. When it starts, it should work correctly.

**Comment by richp10** [comment]
mm sorry - have now tried that and it made no difference.  Double checked that I moved them to the ejabbed ebin directory, file permissions fine..

**Comment by rrigoni** [comment]
I compiled ejabberd_auth_http from source using ejabberd 15.07 and copied to ebin directory and I'm getting the same error.

**Comment by badlop** [comment]
> Ejabberd loads, with only the following error..

That error message only informs you about possible unused options. I've fixed that, so modules installed by ext_mod don't provoke such error messages: a50f00f9e8360ed0d6e1c7791d2226f8663fd285

If you want to try, follow this:
1. Apply that recent fix to your ejabberd
2. Remove the dir and files in $HOME/.ejabberd-modules/ejabberd_auth_http/
3. Start ejabberd
4. Run this: ejabberdctl module_install ejabberd_auth_http
5. Restart ejabberd
6. No error message should appear. Otherwise report here.
7. And http auth should work, otherwise start a new ticket.

**Comment by Hassnain-Raza-Alvi** [comment]
I am having same issue on ejabberd 17.04.
I followed the steps above but it does not solve the problem
