### ISSUE TITLE
Cannot start mod_log_chat.erl with included configuration

### ISSUE THREAD

**Issue by mremond** [processone/ejabberd-contrib#121]
When trying to start `mod_log_chat.erl` with included configuration, the following error is reported:

```
src/mod_log_chat.erl:3: Warning: Non-UTF-8 character(s) detected, but no encoding declared. Encode the file in UTF-8 or add "%% coding: latin-1" at the beginning of the file. Retrying with latin-1 encoding.
Problem 'exit "Cannot load /opt/ejabberd-15.07/.ejabberd-modules/mod_log_chat/conf/mod_log_chat.yml: Syntax error on line 4 at position 8: mapping values are not allowed in this context"' occurred executing the command.
Stacktrace: [{ejabberd_config,exit_or_halt,1,
                              [{file,"src/ejabberd_config.erl"},{line,365}]},
             {ejabberd_config,include_config_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,419}]},
             {lists,flatmap,2,[{file,"lists.erl"},{line,1248}]},
             {ejabberd_config,include_config_files,1,
                              [{file,"src/ejabberd_config.erl"},{line,383}]},
             {ejabberd_config,read_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,123}]},
             {ejabberd_config,load_file,1,
                              [{file,"src/ejabberd_config.erl"},{line,141}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,167}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]}]
```

There also seems to be UTF-8 encoding issue in the source file for `mod_log_chat.erl`.

**Comment by zinid** [comment]
It's easy to fix, the problem is at this line: https://github.com/processone/ejabberd-contrib/blob/master/mod_log_chat/src/mod_log_chat.erl#L3

**Comment by wallacms** [comment]
This seems to fix the first problem (latin-1 characters) but not the second problem.  I still get the same error about the configuration file.  

Problem 'exit "Cannot load /opt/ejabberd-15.07/.ejabberd-modules/mod_log_chat/conf/mod_log_chat.yml: Syntax error on line 4 at position 8: mapping values are not allowed in this context"' occurred executing the command.
Stacktrace: [{ejabberd_config,exit_or_halt,1,
                              [{file,"src/ejabberd_config.erl"},{line,365}]},
             {ejabberd_config,include_config_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,419}]},
             {lists,flatmap,2,[{file,"lists.erl"},{line,1248}]},
             {ejabberd_config,include_config_files,1,
                              [{file,"src/ejabberd_config.erl"},{line,383}]},
             {ejabberd_config,read_file,2,
                              [{file,"src/ejabberd_config.erl"},{line,123}]},
             {ejabberd_config,load_file,1,
                              [{file,"src/ejabberd_config.erl"},{line,141}]},
             {ext_mod,install,1,[{file,"src/ext_mod.erl"},{line,167}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]}]

**Comment by wallacms** [comment]
Removing the comment lines (starting with ';') got rid of the above error, but now I have new errors in my log

2015-09-15 13:53:54.554 [warning] <0.38.0>@gen_mod:validate_opts:256 module 'mod_log_chat' doesn't export mod_opt_type/1
2015-09-15 13:53:54.554 [warning] <0.38.0>@gen_mod:validate_opts:256 module 'mod_log_chat' doesn't export mod_opt_type/1
2015-09-15 13:53:54.567 [warning] <0.38.0>@gen_mod:validate_opts:256 module 'mod_log_chat' doesn't export mod_opt_type/1
2015-09-15 13:53:54.567 [warning] <0.38.0>@gen_mod:validate_opts:256 module 'mod_log_chat' doesn't export mod_opt_type/1
2015-09-15 13:53:54.567 [critical] <0.38.0>@gen_mod:start_module:107 Problem starting the module mod_log_chat for host <<"ccmtrading.com">>
 options: [{path,<<"/var/log/ejabberd/chat">>},{format,html}]
 error: badarg
[{erlang,register,['mod_log_chat_ccmtrading.com',<0.440.0>],[]},
 {mod_log_chat,start_vh,2,[{file,"src/mod_log_chat.erl"},{line,56}]},
 {gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,99}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
 {ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,72}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,272}]}]
2015-09-15 13:53:54.567 [critical] <0.38.0>@gen_mod:start_module:112 ejabberd initialization was aborted because a module start failed.

I added the following lines in the modules section of my ejabberd.conf file:

mod_log_chat:
  path: "/var/log/ejabberd/chat"
  format: html

I'm not sure if this was the right thing to do because it seems like there is a config included with the module.  However if I remove these lines, the module doesn't appear to get loaded.

**Comment by badlop** [comment]
You're right, the characters ; were wrong, they should be # instead. And mod_opt_type was missing in the module. Basically, that module has not been used since many time ago.

Those problems are fixed now in git, and the module seems to work. At least it logs a html file in my tests.

> I added the following lines in the modules section

Yes, you can either accept the default configuration, or add your own.

**Comment by wallacms** [comment]
I'm still getting this after upgrading:
<pre>
[critical] <0.38.0>@gen_mod:start_module:107 Problem starting the module mod_log_chat for host <<"ccmtrading.com">>
options: [{path,<<"/var/log/ejabberd/chat">>},{format,html}]
error: badarg
[{erlang,register,['mod_log_chat_ccmtrading.com',<0.440.0>],[]},
{mod_log_chat,start_vh,2,[{file,"src/mod_log_chat.erl"},{line,56}]},
{gen_mod,start_module,3,[{file,"src/gen_mod.erl"},{line,99}]},
{lists,foreach,2,[{file,"lists.erl"},{line,1336}]},
{ejabberd_app,start,2,[{file,"src/ejabberd_app.erl"},{line,72}]},
{application_master,start_it_old,4,
[{file,"application_master.erl"},{line,272}]}]
</pre>

Note I only see this when I add the module configuration to my ejabberd.yml file.  When I don't have this section the module doesn't appear to be loaded at all - no logs are created and there is no indication in my ejabberd.log that it has been loaded.

**Comment by badlop** [comment]
Ah, I see. This error appears because the module is already started. It was enabled and configured in $HOME/.ejabberd-modules/mod_log_chat/conf/mod_log_chat.yml

So, better modify the options in that file, instead of enabling the module in your main ejabberd.yml

Also note this problem: that config file will get updated (and overwritten!!) when you run "ejabberdctl module_upgrade mod_log_chat"

**Comment by badlop** [comment]
About what I last commented:
EJAB-1746 Improve external module configuration management
https://support.process-one.net/browse/EJAB-1746
